plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'de.oberamsystems'
version = '0.0.1-SNAPSHOT'
description = 'service monitoring software'
compileJava.options.encoding = 'UTF-8'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-mail'
	//implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
	implementation("org.thymeleaf:thymeleaf:3.1.5.RELEASE")
	implementation 'org.webjars:bootstrap:5.3.7'
	implementation 'org.postgresql:postgresql:42.7.11'
	implementation 'jakarta.mail:jakarta.mail-api:2.1.5'
	//implementation 'ch.qos.logback:logback-core:1.5.18'
	implementation 'org.hibernate.orm:hibernate-core:7.4.1.Final'
	//implementation 'org.postgresql:postgresql'
	runtimeOnly 'com.h2database:h2:2.4.240'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	//testImplementation 'org.springframework.security:spring-security-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

tasks.withType(JavaCompile) {
    options.compilerArgs += ['-Xlint:unchecked']
}

task getDeps(type: Copy) {
  from sourceSets.main.runtimeClasspath
  into 'runtime/'
}
